### ISSUE TITLE
Can't find the settings text file

### ISSUE THREAD

**Issue by SamStyles** [kuroni/bongocat-osu#36]
I don't know if it's me but I downloaded the .rar, extracted, and the config.json file is just not there in the folder. I didn't move it or anything. (windows 10)

**Comment by PiouPiou960** [comment]
same pls help

**Comment by kuroni** [comment]
Okay, this is mostly fault on my side. I designed the program so that there is no pre-shipped `config.json`, you can do it on your own.

But looks like a lot of people is confused by this, so I will schedule a release later. For now, you can (and have to), create such a file in the folder following the guide [here](https://github.com/kuroni/bongocat-osu/wiki/Settings).

**Comment by PiouPiou960** [comment]
ok thanks :)
